 channels:
     - conda-forge
 dependencies:
     - cmake
     - dlib==19.4
     - numpy
     - opencv
     - streamlit
     - pip==22.1.2
     - pip:
       - face_recognition
       - wheel
       - datetime
       - Image
       