 channels:
     - conda-forge
 dependencies:
     - numpy
     - opencv
     - streamlit
     - pip==22.1.2
     - pip:
       - cmake
       - dlib=19.4
       - face_recognition
       - datetime
       - Image
       