 channels:
     - conda-forge
 dependencies:
     - dlib
     - numpy
     - opencv
     - face_recognition
     - streamlit
     - pip
     - pip:
       - datetime
       - Image
       - streamlit-webrtc==0.34.2