 channels:
     - conda-forge
 dependencies:
     - dlib
     - numpy
     - opencv
     - streamlit
     - pip
     - pip:
       - datetime
       - Image
       - cmake
       - face_recognition