 channels:
     - conda-forge
 dependencies:
     - pip
     - pip:
       - wheel
       - cmake
     - dlib
     - numpy
     - opencv
     - streamlit
     - pip:
       - face_recognition
       - datetime
       - Image
       