 channels:
     - conda-forge
 dependencies:
     - cmake
     - dlib
     - face_recognition
     - numpy
     - opencv
     - streamlit
     - pip
     - pip:
       - datetime
       - Image
       