 channels:
     - conda-forge
 dependencies:
     - cmake
     - dlib
     - face_recognition
     - numpy
     - opencv
     - streamlit
     - pip==22.1.2
     - pip:
       - wheel
       - datetime
       - Image
       